apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-project-ml
  labels:
    app: tom-project-ml
  namespace: default
spec:
  progressDeadlineSeconds: 3600
  replicas: 3
  selector:
    matchLabels:
      app: tom-project-ml
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tom-project-ml
    spec:
      containers:
        - image: tungthanh97/tom-project-ml:latest
          imagePullPolicy: Always
          name: tom-project-ml
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: tom-project-ml
  labels:
    app: tom-project-ml
spec:
  type: LoadBalancer
  selector:
    app: tom-project-ml
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
