apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-classification
  labels:
    app: ml-classification
  namespace: default
spec:
  progressDeadlineSeconds: 3600
  replicas: 3
  selector:
    matchLabels:
      app: ml-classification
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ml-classification
    spec:
      containers:
        - image: tungthanh97/ml-classification:latest
          imagePullPolicy: Always
          name: ml-classification
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: ml-classification
  labels:
    app: ml-classification
spec:
  type: LoadBalancer
  selector:
    app: ml-classification
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
