apiVersion: v1
kind: Service
metadata:
  name: tom-project-ml
  labels:
    app: tom-project-ml
spec:
  type: LoadBalancer
  selector:
    app: tom-project-ml
  ports:
    - port: 80
      targetPort: 80
