apiVersion: v1
kind: Service
metadata:
  name: ml-classification
  labels:
    app: ml-classification
spec:
  type: LoadBalancer
  selector:
    app: ml-classification
  ports:
    - port: 80
      targetPort: 80
